### ISSUE TITLE
opencv library implementation request!

### ISSUE THREAD

**Issue by dngkatn** [PrasoonDhaneshwar/PanoramaStitching-Android-OpenCV#1]
Hi, 
Thank you for sharing this project. 
My goal is to implement a stitching application using openCV.
As a result of checking your code, it seems that the opencv implementation unit is excluded. 
Can you share it with me so that I can refer to the opencv implementation?

Best regards,

**Comment by PrasoonDhaneshwar** [comment]
In my implementation, I've done JNI calls to OpenCV methods.
Officially, OpenCV does not offer such a solution to do implementation in build.gradle.
Regardless, you can follow this SO link to implement in your project and call the stitcher functions normally in Java.
https://stackoverflow.com/questions/17767557/how-to-use-opencv-in-using-gradle
